services:
  stack:
    image: stack
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  mysql:
    image: mysql
    # Don't use mysl_native_password
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306:3306
